spring:
  application:
    name: upload-service

  datasource:
    url: jdbc:postgresql://localhost:5432/opensans-media
    username: postgres
    password: 8275097876

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: store-media

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  topic:
    upload-media: upload-media
    analysis-stored: analysis-stored


server:
  port: 8082
