spring:
  application:
    name: smart-service

  main:
    web-application-type: reactive

  datasource:
    url: jdbc:postgresql://localhost:5432/opensans-media  # same DB as UploadService
    username: postgres
    password: 8275097876

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.6-flash
        embedding:
          options:
            model: text-embedding-004

    vectorstore:
      pgvector:
        initialize-schema: true          # auto-creates vector_store table on startup
        index-type: HNSW                 # fast approximate nearest neighbour index
        distance-type: COSINE_DISTANCE   # best for semantic similarity
        dimensions: 768

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: smart-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.SmartService.model.MediaAnalysisStoreEvent
        spring.json.trusted.packages: "*"


kafka:
  topic:
    analysis-stored: analysis-stored

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8084


